<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="95822" started-at="2019-09-22T09:41:03 IST" finished-at="2019-09-22T09:42:38 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="95822" started-at="2019-09-22T09:41:03 IST" finished-at="2019-09-22T09:42:38 IST">
      <class name="Fourstay.HomePage">
        <test-method status="PASS" signature="initialize()[pri:0, instance:Fourstay.HomePage@5fbdfdcf]" name="initialize" is-config="true" duration-ms="43636" started-at="2019-09-22T09:41:03 IST" finished-at="2019-09-22T09:41:46 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="basepageNavigationFILE()[pri:0, instance:Fourstay.HomePage@5fbdfdcf]" name="basepageNavigationFILE" duration-ms="11042" started-at="2019-09-22T09:41:46 IST" finished-at="2019-09-22T09:41:57 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- basepageNavigationFILE -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:Fourstay.HomePage@5fbdfdcf]" name="teardown" is-config="true" duration-ms="2397" started-at="2019-09-22T09:41:57 IST" finished-at="2019-09-22T09:42:00 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:Fourstay.HomePage@5fbdfdcf]" name="initialize" is-config="true" duration-ms="27064" started-at="2019-09-22T09:42:00 IST" finished-at="2019-09-22T09:42:27 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="loginPageLoginStatusAssertused()[pri:0, instance:Fourstay.HomePage@5fbdfdcf]" name="loginPageLoginStatusAssertused" duration-ms="8906" started-at="2019-09-22T09:42:27 IST" finished-at="2019-09-22T09:42:36 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Invalid credentials. Please try again.(remove)] but found [Invalid credentials. Please try again.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Invalid credentials. Please try again.(remove)] but found [Invalid credentials. Please try again.]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at Fourstay.HomePage.loginPageLoginStatusAssertused(HomePage.java:164)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPageLoginStatusAssertused -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:Fourstay.HomePage@5fbdfdcf]" name="teardown" is-config="true" duration-ms="2101" started-at="2019-09-22T09:42:36 IST" finished-at="2019-09-22T09:42:38 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- Fourstay.HomePage -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
